company_manager/company_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("crm.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('i18n/', include('django.conf.urls.i18n')),
]

company_manager/crm/urls.py
from django.urls import path
import crm.views as views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("company/create", views.CompanyCreateView.as_view(), name="create_company"),
    path("company/list/", views.CompanyListView.as_view(), name="company_list"),
    path("opportunity/create", views.OpportunityCreateView.as_view(), name="create_opportunity"),
    path("opportunity/opportunities", views.OpportunityListView.as_view(), name="opportunity_list"),
    path("opportunity/update/<int:pk>", views.OpportunityUpdateView.as_view(), name="update_opportunity"),
    path("employee/", views.EmployeeUpdateView.as_view(), name="update_employee"),
    path("register", views.RegisterView.as_view(), name="register")
]

company_manager/crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _


class Address(models.Model):
    street = models.CharField(max_length=200, blank=True, null=True)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        verbose_name = _("Address")
        verbose_name_plural = _("Addresses")


class Company(models.Model):
    status_choices = (
        ("N", "New"),
        ("L", "Lead"),
        ("O", "Opportunity"),
        ("C", "Customer"),
        ("FC", "Former Customer"),
        ("I", "Inactive"),
    )

    name = models.CharField(_("Name"), max_length=50)
    status = models.CharField(_("Status"), max_length=2, default="N", choices=status_choices)
    phone_number = models.CharField(_("Phone_number"), max_length=20, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    identification_number = models.CharField(max_length=100, default="00000000")
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    primary_company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    email = models.CharField(max_length=50)


class Opportunity(models.Model):
    status_choices = (
        ("1", "Prospecting"),
        ("2", "Analysis"),
        ("3", "Proposal"),
        ("4", "Negotiation"),
        ("5", "Closed Won"),
        ("0", "Closed Lost"),
    )

    company = models.ForeignKey(Company, on_delete=models.RESTRICT)
    sales_manager = models.ForeignKey(User, on_delete=models.RESTRICT)
    primary_contact = models.ForeignKey(Contact, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=2, default="1", choices=status_choices)
    value = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    def __str__(self):
        return self.company.name


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    office_number = models.CharField(max_length=10, blank=True, null=True)
    manager = models.ForeignKey("Employee", on_delete=models.SET_NULL, null=True, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Employee.objects.create(user=instance)


@receiver(post_save, sender=Opportunity)
def create_opportunity(sender, instance, created, **kwargs):
    if created:
        send_mail("Opportunity was created", instance.company.name, "test@mojefirma.cz", ["manazer@mojefirma.cz"])

company_manager/crm/forms.py
from django.forms import ModelForm, ValidationError
from crm.models import Employee, Company
from django.contrib.auth.models import User
from django.forms import CharField
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit, Div


class CompanyForm(ModelForm):
    def clean_identification_number(self):
        identification_number = self.cleaned_data["identification_number"]

        if len(identification_number) != 8:
            raise ValidationError("Identification number has incorrect length!")
        return identification_number

    class Meta:
        model = Company
        fields = ["name", "status", "phone_number", "email", "identification_number"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Div("name", css_class="col-4"),
                Div("status", css_class="col-2"),
                Div("identification_number", css_class="col-4"),
                Div("email", css_class="col-4"),
                Div("phone_number", css_class="col-4"),
                css_class="row",
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class='button')
            )
        )


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = ("department", "phone_number")


class RegisterUserForm(UserCreationForm):
    username = CharField(label="Email")

    class Meta:
        model = User
        fields = ("Username", "password1", "password2")

company_manager/crm/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, TemplateView, UpdateView
import crm.models as models
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext as _
from crm.forms import CompanyForm
from crm.forms import RegisterUserForm


class IndexView(TemplateView):
    template_name = "index.html"


class CompanyCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "company/create_company.html"
    form_class = CompanyForm
    success_url = reverse_lazy("index")
    # Translators: This message is shown after successful creation of a company.
    success_message = _("Company was created successfully.")


class CompanyListView(LoginRequiredMixin, ListView):
    model = models.Company
    template_name = "company/company_list.html"


class OpportunityCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    permission_required = "crm.add_opportunity"
    model = models.Opportunity
    template_name = "opportunity/create_opportunity.html"
    fields = ["company", "sales_manager", "description", "status", "value"]
    success_url = reverse_lazy("index")
    success_message = "Opportunity was created successfully."


class OpportunityUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = "crm.change_opportunity"
    model = models.Opportunity
    template_name = "opportunity/update_opportunity.html"
    fields = ["company", "sales_manager", "description", "status", "value"]
    success_url = reverse_lazy("opportunity_list")


class OpportunityListView(ListView):
    model = models.Opportunity
    template_name = "opportunity/opportunity_list.html"


class EmployeeUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    fields = ["department", "phone_number", "office_number", "manager"]
    template_name = "employee/update_employee.html"
    success_url = reverse_lazy("index")
    success_message = "Data was updated successfully."

    def get_object(self, queryset=None):
        return self.request.user.employee


class RegisterView(CreateView):
    form_class = RegisterUserForm
    success_url = reverse_lazy("login")
    template_name = "registration/register.html"

company_manager/crm/templates/base.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Company Manager</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
{% if messages %}
{% for item in messages %}
<div class="alert alert-success" roll="alert">{{ item }}</div>
{% endfor %}
{% endif %}

<nav class="navbar navbar-expand-sm bg-light">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url 'index' %}" role="button"  aria-expanded="false">
                  {% trans "Home" %}
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {% trans "Companies" %}
              </a>
                  <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href='{% url "company_list" %}'>{% trans "List of companies" %}</a></li>
                      {% if perms.crm.add_company %}
                      <li><a class="dropdown-item" href='{% url "create_company" %}'>{% trans "Create company" %}</a></li>
                      {% endif %}
                  </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {% trans "Opportunity" %}
              </a>
                  <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href='{% url "opportunity_list" %}'>{% trans "List of the opportunities" %}</a></li>
                      {% if perms.crm.add_opportunity %}
                      <li><a class="dropdown-item" href='{% url "create_opportunity" %}'>{% trans "Create opportunity" %}</a></li>
                      {% endif %}
                  </ul>
            </li>
        </ul>

        {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Odhlášení</a>
        {% else %}
            <a class="nav-link" href="{% url 'login' %}">Přihlášení</a>
        {% endif %}


    </div>
</nav>

{% block content %}

{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

company_manager/crm/templates/company/company_list.html
{% extends "base.html" %}
{% block content %}

    <h1>List of the companies</h1>
    <ul>
    {% for item in object_list %}
    <li>{{ item.name }}</li>
    {% endfor %}
    </ul>
{% endblock %}

company_manager/crm/templates/company/create_company.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h1>Registration of the new company</h1>
<form method="post">
    {% csrf_token %}
    {% crispy form %}
</form>
{% endblock %}

company_manager/crm/templates/employee/update_employee.html
{% extends "base.html" %}
{% block content %}

<h1>Update employee</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

company_manager/crm/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<h1>{% trans "Welcome" %}</h1>
<form action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go">
</form>
{% endblock %}

company_manager/crm/templates/opportunity/create_opportunity.html
{% extends "base.html" %}
{% block content %}

<h1>Registration of the new opportunity</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Uložit</button>
</form>
{% endblock %}

company_manager/crm/templates/opportunity/opportunity_list.html
{% extends "base.html" %}
{% block content %}

    <h1>Opportunity list</h1>
    <ul>
    {% if object_list %}
        {% for item in object_list %}
            <li>{{ item.company.name }} - <a class="link" href="/opportunity/update/{{item.pk}}">Upravit</a></li>
        {% endfor %}
        {% else %}
            <li>Žádné příležitosti k dispozici</li>
    {% endif %}
    </ul>
{% endblock %}

company_manager/crm/templates/opportunity/update_opportunity.html
{% extends "base.html" %}
{% block content %}

<h1>Úprava obchodního případu</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Upravit</button>
</form>
{% endblock %}